In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [3]:
item_list=[['bread','butter','jam','milk'],
           ['bread','butter','milk'],
           ['bread','juice','curd'],
           ['bread','milk','juice'],
           ['butter','milk','juice']]

In [6]:
encoder =  TransactionEncoder()
data = encoder.fit_transform(item_list)
col_names = encoder.columns_
df = pd.DataFrame(data,columns=col_names)
df

   bread  butter   curd    jam  juice   milk
0   True    True  False   True  False   True
1   True    True  False  False  False   True
2   True   False   True  False   True  False
3   True   False  False  False   True   True
4  False    True  False  False   True   True

In [5]:
frequent_items = apriori(df,min_support=0.5,use_colnames=True)
frequent_items

   support                   itemsets
0      0.8         frozenset({bread})
1      0.6        frozenset({butter})
2      0.6         frozenset({juice})
3      0.8          frozenset({milk})
4      0.6   frozenset({milk, bread})
5      0.6  frozenset({milk, butter})

In [7]:
rules = association_rules(frequent_items,metric='confidence',min_threshold=0.5)
rules = rules.sort_values(['confidence','lift'],ascending=[False,False])
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
3,frozenset({butter}),frozenset({milk}),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
2,frozenset({milk}),frozenset({butter}),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
0,frozenset({milk}),frozenset({bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
1,frozenset({bread}),frozenset({milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [8]:
x=rules.iloc[:,[0,1,4,5]]
x

           antecedents          consequents  support  confidence
3  frozenset({butter})    frozenset({milk})      0.6        1.00
2    frozenset({milk})  frozenset({butter})      0.6        0.75
0    frozenset({milk})   frozenset({bread})      0.6        0.75
1   frozenset({bread})    frozenset({milk})      0.6        0.75

## Fp growth

In [9]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth,association_rules

In [10]:
item_list=[['bread','butter','jam','milk'],
           ['bread','butter','milk'],
           ['bread','juice','curd'],
           ['bread','milk','juice'],
           ['butter','milk','juice']]

In [12]:
encoder =  TransactionEncoder()
data = encoder.fit_transform(item_list)
col_names = encoder.columns_
df = pd.DataFrame(data,columns=col_names)
df

   bread  butter   curd    jam  juice   milk
0   True    True  False   True  False   True
1   True    True  False  False  False   True
2   True   False   True  False   True  False
3   True   False  False  False   True   True
4  False    True  False  False   True   True

In [13]:
frequent_items = fpgrowth(df,min_support=0.5,use_colnames=True)
frequent_items

   support                   itemsets
0      0.8          frozenset({milk})
1      0.8         frozenset({bread})
2      0.6        frozenset({butter})
3      0.6         frozenset({juice})
4      0.6   frozenset({milk, bread})
5      0.6  frozenset({milk, butter})

In [14]:
rules = association_rules(frequent_items,metric='confidence',min_threshold=0.5)
rules = rules.sort_values(['confidence','lift'],ascending=[False,False])
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
3,frozenset({butter}),frozenset({milk}),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
2,frozenset({milk}),frozenset({butter}),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
0,frozenset({milk}),frozenset({bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
1,frozenset({bread}),frozenset({milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [15]:
x=rules.iloc[:,[0,1,4,5]]
x

           antecedents          consequents  support  confidence
3  frozenset({butter})    frozenset({milk})      0.6        1.00
2    frozenset({milk})  frozenset({butter})      0.6        0.75
0    frozenset({milk})   frozenset({bread})      0.6        0.75
1   frozenset({bread})    frozenset({milk})      0.6        0.75