## Car category classification using Random Forest Classifier

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data=pd.read_csv('data/global_cars_enhanced.csv')
data.head()

,Car_ID,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score
0,CAR_0001,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA,20,Premium,0.1338,Old,0.35
1,CAR_0002,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA,3,Premium,0.0362,New,0.75
2,CAR_0003,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China,19,Premium,0.0610,Old,0.30
3,CAR_0004,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA,13,Mid-Range,0.2033,Old,0.30
4,CAR_0005,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK,17,Premium,0.0622,Old,0.90

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Car_ID                 300 non-null    str
 1   Brand                  300 non-null    str
 2   Manufacture_Year       300 non-null    int64
 3   Body_Type              300 non-null    str
 4   Fuel_Type              300 non-null    str
 5   Transmission           300 non-null    str
 6   Engine_CC              300 non-null    int64
 7   Horsepower             300 non-null    int64
 8   Mileage_km_per_l       300 non-null    int64
 9   Price_USD              300 non-null    int64
 10  Manufacturing_Country  300 non-null    str
 11  Car_Age                300 non-null    int64
 12  Price_Category         300 non-null    str
 13  HP_per_CC              300 non-null    float64
 14  Age_Category           300 non-null    str
 15  Efficiency_Score       300 non-null    float64
dtypes: float64(2), int64(6), str(8)
memory usage: 37.6 KB

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Car_ID                 300 non-null    str
 1   Brand                  300 non-null    str
 2   Manufacture_Year       300 non-null    int64
 3   Body_Type              300 non-null    str
 4   Fuel_Type              300 non-null    str
 5   Transmission           300 non-null    str
 6   Engine_CC              300 non-null    int64
 7   Horsepower             300 non-null    int64
 8   Mileage_km_per_l       300 non-null    int64
 9   Price_USD              300 non-null    int64
 10  Manufacturing_Country  300 non-null    str
 11  Car_Age                300 non-null    int64
 12  Price_Category         300 non-null    str
 13  HP_per_CC              300 non-null    float64
 14  Age_Category           300 non-null    str
 15  Efficiency_Score       300 non-null    float64
dtypes: float64(2), int64(6), str(8)
memory usage: 37.6 KB

In [6]:
data=data.drop(['Car_ID'], axis=1)

In [7]:
data['Price_Category'].value_counts()

Price_Category
Budget       78
Mid-Range    75
Premium      74
Luxury       73
Name: count, dtype: int64

In [8]:
oe= OrdinalEncoder(categories=[['Budget', 'Mid-Range', 'Premium','Luxury']])
data['Price_Category']=oe.fit_transform(data[['Price_Category']])
data.head()

,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score
0,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA,20,2.0,0.1338,Old,0.35
1,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA,3,2.0,0.0362,New,0.75
2,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China,19,2.0,0.0610,Old,0.30
3,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA,13,1.0,0.2033,Old,0.30
4,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK,17,2.0,0.0622,Old,0.90

In [9]:
le= LabelEncoder()
data['Age_Category']=le.fit_transform(data['Age_Category'])
data.head()

,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score
0,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA,20,2.0,0.1338,2,0.35
1,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA,3,2.0,0.0362,1,0.75
2,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China,19,2.0,0.0610,2,0.30
3,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA,13,1.0,0.2033,2,0.30
4,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK,17,2.0,0.0622,2,0.90

In [10]:
dff= pd.get_dummies(data, dtype=int)
dff.head()

,Manufacture_Year,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score,...,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Manufacturing_Country_China,Manufacturing_Country_Germany,Manufacturing_Country_Japan,Manufacturing_Country_South Korea,Manufacturing_Country_UK,Manufacturing_Country_USA
0,2006,4089,547,17,73407,20,2.0,0.1338,2,0.35,...,0,1,0,1,0,0,0,0,0,1
1,2023,4618,167,25,79370,3,2.0,0.0362,1,0.75,...,0,1,1,0,0,0,0,0,0,1
2,2007,1802,110,16,76549,19,2.0,0.0610,2,0.30,...,0,0,0,1,1,0,0,0,0,0
3,2013,1835,373,16,48722,13,1.0,0.2033,2,0.30,...,0,1,0,1,0,0,0,0,0,1
4,2009,2332,145,28,83265,17,2.0,0.0622,2,0.90,...,1,0,1,0,0,0,0,0,1,0

In [11]:
x=dff.drop('Price_Category', axis=1)
y=dff['Price_Category']
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 36 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Manufacture_Year                   300 non-null    int64
 1   Engine_CC                          300 non-null    int64
 2   Horsepower                         300 non-null    int64
 3   Mileage_km_per_l                   300 non-null    int64
 4   Price_USD                          300 non-null    int64
 5   Car_Age                            300 non-null    int64
 6   HP_per_CC                          300 non-null    float64
 7   Age_Category                       300 non-null    int64
 8   Efficiency_Score                   300 non-null    float64
 9   Brand_Audi                         300 non-null    int64
 10  Brand_BMW                          300 non-null    int64
 11  Brand_Ford                         300 non-null    int64
 12  Brand_Honda                        300 non-null    int64
 13  Brand_Hyundai                      300 non-null    int64
 14  Brand_Kia                          300 non-null    int64
 15  Brand_Mercedes                     300 non-null    int64
 16  Brand_Nissan                       300 non-null    int64
 17  Brand_Tesla                        300 non-null    int64
 18  Brand_Toyota                       300 non-null    int64
 19  Body_Type_Coupe                    300 non-null    int64
 20  Body_Type_Hatchback                300 non-null    int64
 21  Body_Type_Pickup                   300 non-null    int64
 22  Body_Type_SUV                      300 non-null    int64
 23  Body_Type_Sedan                    300 non-null    int64
 24  Fuel_Type_Diesel                   300 non-null    int64
 25  Fuel_Type_Electric                 300 non-null    int64
 26  Fuel_Type_Hybrid                   300 non-null    int64
 27  Fuel_Type_Petrol                   300 non-null    int64
 28  Transmission_Automatic             300 non-null    int64
 29  Transmission_Manual                300 non-null    int64
 30  Manufacturing_Country_China        300 non-null    int64
 31  Manufacturing_Country_Germany      300 non-null    int64
 32  Manufacturing_Country_Japan        300 non-null    int64
 33  Manufacturing_Country_South Korea  300 non-null    int64
 34  Manufacturing_Country_UK           300 non-null    int64
 35  Manufacturing_Country_USA          300 non-null    int64
dtypes: float64(2), int64(34)
memory usage: 84.5 KB

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain ,xtest,ytrain,ytest= train_test_split(x,y, test_size=0.3, random_state=42)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, precision_score, recall_score

In [15]:
RFCModel=RandomForestClassifier(n_estimators=100, max_depth=5)
RFCModel.fit(xtrain,ytrain)

RandomForestClassifier(max_depth=5)

In [16]:
ypred=RFCModel.predict(xtest)

In [17]:
print('training efficiency:', RFCModel.score(xtrain,ytrain))
print('testing efficiency:', RFCModel.score(xtest, ytest))

training efficiency: 1.0
testing efficiency: 0.9555555555555556

In [18]:
print('confusion_matrix\n', confusion_matrix(ytest, ypred))

confusion_matrix
 [[22  0  0  0]
 [ 0 15  0  0]
 [ 0  2 24  2]
 [ 0  0  0 25]]

In [19]:
print('accuracy_score',accuracy_score(ytest,ypred))
print('precision_score',precision_score(ytest,ypred, average='weighted'))
print('recall_score', recall_score(ytest,ypred, average='weighted'))
print('f1_score', f1_score(ytest,ypred, average='weighted'))

accuracy_score 0.9555555555555556
precision_score 0.9598160251755024
recall_score 0.9555555555555556
f1_score 0.9549679487179488

# car price predicton using Random Forest Regressor

In [20]:
dff.head()

,Manufacture_Year,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score,...,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Manufacturing_Country_China,Manufacturing_Country_Germany,Manufacturing_Country_Japan,Manufacturing_Country_South Korea,Manufacturing_Country_UK,Manufacturing_Country_USA
0,2006,4089,547,17,73407,20,2.0,0.1338,2,0.35,...,0,1,0,1,0,0,0,0,0,1
1,2023,4618,167,25,79370,3,2.0,0.0362,1,0.75,...,0,1,1,0,0,0,0,0,0,1
2,2007,1802,110,16,76549,19,2.0,0.0610,2,0.30,...,0,0,0,1,1,0,0,0,0,0
3,2013,1835,373,16,48722,13,1.0,0.2033,2,0.30,...,0,1,0,1,0,0,0,0,0,1
4,2009,2332,145,28,83265,17,2.0,0.0622,2,0.90,...,1,0,1,0,0,0,0,0,1,0

In [21]:
X=dff.drop('Price_USD', axis=1)
Y= dff['Price_USD']

In [22]:
from sklearn.ensemble import RandomForestRegressor

In [23]:
x_train,x_test,y_train,y_test=train_test_split(X,Y, random_state=42)

In [24]:
RFRmodel=RandomForestRegressor(n_estimators=200, max_depth=5)

In [25]:
RFRmodel.fit(x_train,y_train)

RandomForestRegressor(max_depth=5, n_estimators=200)

In [26]:
y_pred=RFRmodel.predict(x_test)

In [27]:
print('training efficiency: ', RFRmodel.score(x_train,y_train))
print('testing efficiency: ', RFRmodel.score(x_test,y_test))

training efficiency:  0.9760288396770177
testing efficiency:  0.9301070898658573