In [1]:
import pandas as pd 
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv', encoding='ISO-8859-1')
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [4]:
oe=OrdinalEncoder(categories=[['low','medium','high']])
df['salary']=oe.fit_transform(df[['salary']])
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,0.0
1,1005,5,262,6,0,1,0,sales,1.0
2,1486,7,272,4,0,1,0,sales,1.0
3,1038,5,223,5,0,1,0,sales,0.0
4,1057,2,159,3,0,1,0,sales,0.0
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,0.0
14995,87673,2,160,3,0,1,0,support,0.0
14996,87679,2,143,3,0,1,0,support,0.0
14997,87681,6,280,4,0,1,0,support,0.0
14998,87684,2,158,3,0,1,0,support,0.0